### ISSUE TITLE
Seems, the project does not evolve, may be add a disclaimer to the site and README?

### ISSUE THREAD

**Issue by svetlyak40wt** [cl21/cl21#98]

**Comment by vindarel** [comment]
Related to this: https://github.com/cl21/cl21/issues/91 with answers like, march of 2016:

> No more abandoned than usual - I for one use and occasionally commit to this project, and I know I'm not the only one.

**Comment by svetlyak40wt** [comment]
Closing this old issue. Thanks to https://12forks.com MVP for pointing to it.
