### ISSUE TITLE
Can not install lparallel alongside CL21 (solution found. Bug ?)

### ISSUE THREAD

**Issue by vindarel** [cl21/cl21#99]
I have a weird mix of errors.

I was using CL21, I was in my package, and I wanted to install lparallel. Not possible:

```
(ql:quickload :lparallel)
To load "lparallel":
  Load 1 ASDF system:
    lparallel
; Loading "lparallel"
; 
; caught ERROR:
;   DYNAMIC-EXTENT on a weird thing: (CL21.CORE.FUNCTION:FUNCTION #:BODY-FN1)
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition
; Evaluation aborted on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1008956C13}>.
```

I can reproduce it in a new session but it's a bit weird: if I `quickload` lparallel in `cl-user`, it complains on not finding the symbol `CL21.CORE.FUNCTION`:

>  The name "CL21.CORE.FUNCTION" does not designate any package.

So I ql:quickload CL21 and then on retrying to load lparallel (this time in `cl-user`) I get the first error.

But, I tried in Portacle for a fresh image and… I couldn't reproduce this.

Any idea ? Is that an issue with cl21, lparallel, quicklisp or asdf ?? Thanks.

**Comment by phoe** [comment]
> I can reproduce it in a new session but it's a bit weird: if I quickload lparallel in cl-user, it complains on not finding the symbol CL21.CORE.FUNCTION:
>    The name "CL21.CORE.FUNCTION" does not designate any package.

Remove your .fasl files and try again or `(asdf:operate 'asdf:load-op :lparallel :force t)` to force a recompilation of the lparallel system.

Sounds like a cl21 bug.

**Comment by vindarel** [comment]
I tried with this command and it works again. I loaded cl21, `use-package`, `in-package` then loading lparallel still worked. This makes me load lparallel in a new or in my old session. Thanks !

ps: cl21 is a pleasure to work with :)
